# -*- coding: utf-8 -*-
"""streamlit_tennis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://github.com/rajinipreethajohn/Tennis_GrandSlams_Plotly/blob/main/Mens_Tennis_Grand_Slam_Winner.csv
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Load your tennis dataset into a DataFrame (e.g., df)
df = pd.read_csv('/content/Mens_Tennis_Grand_Slam_Winner.csv')

# Define the Grand Slam tournaments
grand_slams = ['Wimbledon', 'US Open', 'French Open', 'Australian Open']

# Filter data for the Grand Slam tournaments
df_grand_slams = df[df['TOURNAMENT'].isin(grand_slams)]

# Create a custom text column with rotated labels
df_grand_slams['WINNER_TEXT'] = df_grand_slams['WINNER'] + '<br>' + df_grand_slams['YEAR'].astype(str)

# Streamlit app header
st.title('Grand Slam Winners Visualization')

# Year selection using a slider
selected_year = st.slider('Select a Year', min_value=1950, max_value=2023, value=2023)

# Create an interactive line plot based on the selected year
filtered_df = df_grand_slams[df_grand_slams['YEAR'] <= selected_year]
fig = px.line(filtered_df, x='YEAR', y='WINNER', color='TOURNAMENT',
            title=f'Grand Slam Winners by Year (up to {selected_year})', labels={'WINNER': 'Winner'})

# Customize the plot layout
fig.update_traces(mode='lines+markers', marker=dict(size=7), textposition='top center', textfont=dict(size=10))
fig.update_xaxes(title='Year', tickangle=45)
fig.update_yaxes(title='Winner')

# Set custom text column as hover text
fig.update_traces(text=filtered_df['WINNER_TEXT'])

# Show the interactive plot
st.plotly_chart(fig)

# Additional content or explanations can be added here
st.write(f'This interactive chart shows Grand Slam winners by year for different tournaments up to {selected_year}.')

# Add any other Streamlit components or explanations as needed
